import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { authenticate, isAuthenticated, logout, user } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isAuthenticated ? (
        <div>
          <button onClick={logout}>Logout</button>
          <p>Username: {user?.getUsername()}</p>
          <p>Wallet Address: {user?.get("ethAddress")}</p>
        </div>
      ) : (
        <button onClick={() => authenticate()}>Login</button>
      )}
    </div>
  );
}
